export * as login from "./login";
export * as user from "./user";
export * as course from "./course";
export * as system from "./system";
export * as role from "./role";
export * as viewBlock from "./viewBlock";
export * as order from "./order";
export * as search from "./search";
export * as comment from "./comment";
