name: MeEdu

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  meedu-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.3, 7.4 ]

    steps:
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ matrix.php-version }}
      - name: 'Setup MySQL'
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8mb4'
          mysql version: '5.6'
          mysql database: 'meedu'
          mysql root password: 'root'
      - uses: actions/checkout@v2
      - name: 'Copy .env'
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: 'Install Dependencies'
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: 'Generate key'
        run: php artisan key:generate
      - name: 'Directory Permissions'
        run: chmod -R 777 storage bootstrap/cache
      - name: 'Execute tests (Unit and Feature tests) via PHPUnit'
        env:
          WECHAT_MP_APP_ID: ${{secrets.WECHAT_MP_APP_ID}}
          WECHAT_MP_APP_SECRET: ${{secrets.WECHAT_MP_APP_SECRET}}
          WECHAT_MP_TOKEN: ${{secrets.WECHAT_MP_TOKEN}}
        run: vendor/bin/phpunit
